FROM nginx

RUN apt-get update -y && apt-get install bash vim htop aha cron -y

WORKDIR /usr/share/nginx/html

COPY ./html .
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
RUN echo 'admin:$apr1$0IoegFgU$kQL1.bwyweRW6SiuVXKLN1' > /etc/nginx/.htpasswd # admin:secret

COPY ./scripts /scripts
RUN sed -i 's/\r$//' /scripts/*.sh # Fix for windows line end >:(
RUN chmod +x /scripts/*.sh

RUN crontab -l | { cat; echo "* * * * * bash /scripts/htop_html.sh"; } | crontab -
RUN crontab -l | { cat; echo "0 0 * * * bash /scripts/backup.sh"; } | crontab -

EXPOSE 80

# Run cron and nginx in foreground
RUN echo '#!/bin/bash\n\ncron && /docker-entrypoint.sh "$@"' >> /entrypoint-wrapper.sh && chmod +x /entrypoint-wrapper.sh
ENTRYPOINT ["/entrypoint-wrapper.sh"]
CMD ["nginx", "-g", "daemon off;"]
