FROM nginx

RUN apt-get update -y && apt-get install bash vim htop aha cron -y

WORKDIR /usr/share/nginx/html

COPY ./html .
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

COPY ./scripts /scripts
RUN sed -i 's/\r$//' /scripts/*.sh # Fix for windows line end >:(
RUN chmod +x /scripts/*.sh

# COPY ./cron /etc/cron.d
# RUN sed -i 's/\r$//' /etc/cron.d/* # Fix for windows line end >:(
# RUN chmod 0644 /etc/cron.d/*
# RUN crontab /etc/cron.d/*
# RUN touch /var/log/cron.log

RUN crontab -l | { cat; echo "* * * * * bash /scripts/htop_html.sh"; } | crontab -

EXPOSE 80

RUN echo '#!/bin/bash\n\ncron && /docker-entrypoint.sh "$@"' >> /entrypoint-wrapper.sh && chmod +x /entrypoint-wrapper.sh

ENTRYPOINT ["/entrypoint-wrapper.sh"]

CMD ["nginx", "-g", "daemon off;"]
